### ISSUE TITLE
Audio crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#103]
```
2016-08-10 17:20:45,938 : INFO : kivy : Factory: 179 symbols loaded
2016-08-10 17:20:46,157 : INFO : kivy : Image: Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
2016-08-10 17:20:46,531 : INFO : kivy : VideoGstplayer: Using Gstreamer 1.4.5.0
2016-08-10 17:20:46,531 : INFO : kivy : Video: Provider: gstplayer
2016-08-10 17:20:46,625 : INFO : kivy : Loading MPF-MC controller
2016-08-10 17:20:46,625 : INFO : mpfmc : Mission Pinball Framework Media Controller v0.30.0
2016-08-10 17:20:46,625 : INFO : mpfmc : Machine path: C:\nbx
2016-08-10 17:20:46,625 : INFO : mpfmc : Starting clock at 30.0Hz
2016-08-10 17:20:46,640 : INFO : kivy : Text: Provider: sdl2
2016-08-10 17:20:47,561 : INFO : kivy : OSC: using <thread> for socket
2016-08-10 17:20:47,608 : INFO : kivy : Window: Provider: sdl2
2016-08-10 17:20:50,462 : INFO : kivy : GL: GLEW initialization succeeded
2016-08-10 17:20:50,463 : INFO : kivy : GL: OpenGL version <b'3.3.11672 Compatibility Profile Context'>
2016-08-10 17:20:50,463 : INFO : kivy : GL: OpenGL vendor <b'ATI Technologies Inc.'>
2016-08-10 17:20:50,463 : INFO : kivy : GL: OpenGL renderer <b'ATI Radeon HD 3400 Series'>
2016-08-10 17:20:50,464 : INFO : kivy : GL: OpenGL parsed version: 3, 3
2016-08-10 17:20:50,464 : INFO : kivy : GL: Shading version <b'3.30'>
2016-08-10 17:20:50,464 : INFO : kivy : GL: Texture max size <8192>
2016-08-10 17:20:50,464 : INFO : kivy : GL: Texture max units <16>
2016-08-10 17:20:50,526 : INFO : kivy : Shader: fragment shader: <b'Fragment shader was successfully compiled to run on hardware.'>
2016-08-10 17:20:50,602 : INFO : kivy : Shader: vertex shader: <b'Vertex shader was successfully compiled to run on hardware.'>
2016-08-10 17:20:50,702 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:50,704 : INFO : kivy : Window: auto add sdl2 input provider
2016-08-10 17:20:50,705 : INFO : kivy : Window: virtual keyboard not allowed, single mode, not docked
2016-08-10 17:20:51,053 : INFO : AudioInterface : Initialized 0.30.0
2016-08-10 17:20:51,058 : INFO : kivy : Base: Start application main loop
2016-08-10 17:20:51,278 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:51,285 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:51,286 : INFO : kivy : GL: NPOT texture support is available
2016-08-10 17:20:51,297 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:51,301 : INFO : kivy : Shader: fragment shader: <b'Fragment shader was successfully compiled to run on hardware.'>
2016-08-10 17:20:51,309 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:51,446 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:51,453 : INFO : kivy : Shader: program: <Vertex shader(s) linked, fragment shader(s) linked.>
2016-08-10 17:20:56,830 : INFO : MPF-MC BCP Server : Starting up on localhost port 5050
2016-08-10 17:20:56,849 : INFO : MPF-MC BCP Server : Waiting for a connection...
2016-08-10 17:20:57,277 : INFO : MPF-MC BCP Server : Received connection from: 127.0.0.1:51208
2016-08-10 17:21:04,368 : INFO : kivy : GL: Unpack subimage support is available
2016-08-10 17:26:18,726 : INFO : kivy : Base: Leaving application in progress...
2016-08-10 17:26:18,726 : ERROR : kivy : unorderable types: dict() < dict()
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 152, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "c:\python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "c:\python34\lib\site-packages\mpfmc\core\audio\__init__.py", line 186, in tick
    self.audio_interface.process()
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 611, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.AudioInterface.process (mpfmc/core/audio/audio_interface.c:9024)
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1580, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track.process (mpfmc/core/audio/audio_interface.c:15632)
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1619, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track._get_next_sound (mpfmc/core/audio/audio_interface.c:15926)
  File "c:\python34\lib\queue.py", line 195, in get_nowait
    return self.get(block=False)
  File "c:\python34\lib\queue.py", line 177, in get
    item = self._get()
  File "c:\python34\lib\queue.py", line 233, in _get
    return heappop(self.queue)
TypeError: unorderable types: dict() < dict()
2016-08-10 17:26:18,784 : INFO : kivy : Stopping child threads... (3 remaining)
2016-08-10 17:26:19,093 : INFO : MPF-MC BCP Server : Stopping BCP sending thread
2016-08-10 17:26:19,491 : INFO : kivy : All child threads stopped.
```

From: https://groups.google.com/d/msg/mpf-users/r5qFdgJjGL8/jpp9tI2zEgAJ

**Comment by qcapen** [comment]
This bug is caused by setting one of the items in a tuple to None that is currently contained in a priority queue.  This causes the queue not be able to sort the items properly.  The fix will be to set a flag in the tuple item to indicate the item has been canceled rather than setting it to None.

**Comment by qcapen** [comment]
Have not been able to replicate this and Mark has not encountered it again lately.  Nevertheless, the code change made should prevent the issue from reoccurring so this issue will be closed.
