### ISSUE TITLE
KeyError in sound queue when mode stops

### ISSUE THREAD

**Issue by qcapen** [missionpinball/mpf-mc#130]
From Brian Cox in mpf discussion group (https://groups.google.com/forum/#!topic/mpf-users/w6AoYMWtfH8):

DEBUG : Events : vvvv Finished event 'mode_basepurple_started'. Type: None. Callback: None. Args: {}

DEBUG : Events : ^^^^ Processing event 'slides_play'. Type: None, Callback: None, Args: {'context': 'show_30', 'settings': {'tigerredshootnow_slide_1': {'target': None, 'persist': False, 'priority': None, 'force': False, 'expire': None, 'action': 'play', 'transition': {'type': 'move_in', 'easing': 'out_quad', 'direction': 'right', 'duration': 1.0}, 'show': True, 'widgets': [{'adjust_left': None, 'anchor_y': None, 'keep_ratio': False, 'allow_stretch': False, 'reset_animations_events': [], 'image': 'tigerRedMed', 'y': None, 'style': None, 'color': [1.0, 1.0, 1.0, 1.0], 'opacity': 1.0, 'loops': 0, 'height': 0, 'adjust_top': None, 'adjust_right': None, 'start_frame': 0, 'animations': None, 'expire': None, '_default_settings': ['type', 'image', 'z'], 'anchor_x': None, 'auto_play': True, 'key': None, 'z': 4, 'x': None, 'adjust_bottom': None, 'width': 0, 'type': 'image', 'fps': 10}]}}, 'priority': 300}

DEBUG : Events : McConfigPlayer.play_from_trigger (priority: 1) responding to event 'slides_play' with args {'context': 'show_30', 'settings': {'tigerredshootnow_slide_1': {'target': None, 'persist': False, 'priority': None, 'force': False, 'expire': None, 'action': 'play', 'transition': {'type': 'move_in', 'easing': 'out_quad', 'direction': 'right', 'duration': 1.0}, 'show': True, 'widgets': [{'adjust_left': None, 'anchor_y': None, 'keep_ratio': False, 'allow_stretch': False, 'reset_animations_events': [], 'image': 'tigerRedMed', 'y': None, 'style': None, 'color': [1.0, 1.0, 1.0, 1.0], 'opacity': 1.0, 'loops': 0, 'height': 0, 'adjust_top': None, 'adjust_right': None, 'start_frame': 0, 'animations': None, 'expire': None, '_default_settings': ['type', 'image', 'z'], 'anchor_x': None, 'auto_play': True, 'key': None, 'z': 4, 'x': None, 'adjust_bottom': None, 'width': 0, 'type': 'image', 'fps': 10}]}}, 'priority': 300}

DEBUG : Events : vvvv Finished event 'slides_play'. Type: None. Callback: None. Args: {'context': 'show_30', 'settings': {'tigerredshootnow_slide_1': {'target': None, 'persist': False, 'priority': None, 'force': False, 'expire': None, 'action': 'play', 'transition': {'type': 'move_in', 'easing': 'out_quad', 'direction': 'right', 'duration': 1.0}, 'show': True, 'widgets': [{'adjust_left': None, 'anchor_y': None, 'keep_ratio': False, 'allow_stretch': False, 'reset_animations_events': [], 'image': 'tigerRedMed', 'y': None, 'style': None, 'color': [1.0, 1.0, 1.0, 1.0], 'opacity': 1.0, 'loops': 0, 'height': 0, 'adjust_top': None, 'adjust_right': None, 'start_frame': 0, 'animations': None, 'expire': None, '_default_settings': ['type', 'image', 'z'], 'anchor_x': None, 'auto_play': True, 'key': None, 'z': 4, 'x': None, 'adjust_bottom': None, 'width': 0, 'type': 'image', 'fps': 10}]}}, 'priority': 300}

DEBUG : AudioInterface.Track.1.sfx : Next pending sound in queue has been canceled, skipping sound [-100, None, <Sound: chime_10a(4507840352), Loaded=True>, {'volume': 89, 'max_queue_time': None, 'loops': 0}, True]
INFO : kivy : Base: Leaving application in progress...
ERROR : kivy : <Sound: chime_10a(4507840352), Loaded=True>

Traceback (most recent call last):

  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpfmc/commands/mc.py", line 152, in **init**
    thread_stopper=thread_stopper).run()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/app.py", line 828, in run
    runTouchApp()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/base.py", line 327, in idle
    Clock.tick()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/clock.py", line 515, in tick
    self._process_events()

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)

  File "/Applications/MPF.app/Contents/Resources/kivy/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)

  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpfmc/core/audio/**init**.py", line 186, in tick
    self.audio_interface.process()

  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 611, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.AudioInterface.process (mpfmc/core/audio/audio_interface.c:9028)

  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1580, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track.process (mpfmc/core/audio/audio_interface.c:15636)

  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1639, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track._get_next_sound (mpfmc/core/audio/audio_interface.c:16312)

KeyError: <Sound: chime_10a(4507840352), Loaded=True>

INFO : kivy : Stopping child threads... (3 remaining)
INFO : MPF-MC BCP Server : Stopping BCP sending thread
INFO : kivy : All child threads stopped.

This happened a second time, and seems like the crash occurs when there is a sound queue, and then the mode that generated it ends before the sound plays,

**Comment by qcapen** [comment]
Implemented fix in MPF-MC 0.30.4.
