### ISSUE TITLE
Audio Crash TypeError: unorderable types: NoneType() < SoundInstance()

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#208]
ERROR : mpfmc : SoundPlayer: The specified sound does not exist ('sw_beat').
INFO : kivy : Base: Leaving application in progress...
ERROR : kivy : unorderable types: NoneType() < SoundInstance()
Traceback (most recent call last):
  File "mpf-mc/mpfmc/commands/mc.py", line 153, in **init**
    thread_stopper=thread_stopper).run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python3/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python3/dist-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "mpf-mc/mpfmc/core/audio/__init__.py", line 222, in tick
    self.audio_interface.process()
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 638, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.AudioInterface.process (mpfmc/core/audio/audio_interface.c:9819)
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1871, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.TrackStandard.process (mpfmc/core/audio/audio_interface.c:17799)
  File "Pinball\mpf_mc\mpfmc\core\audio\audio_interface.pyx", line 1971, in Pinball.mpf_mc.mpfmc.core.audio.audio_interface.TrackStandard._get_next_sound (mpfmc/core/audio/audio_interface.c:18903)
  File "/usr/lib/python3.4/queue.py", line 195, in get_nowait
    return self.get(block=False)
  File "/usr/lib/python3.4/queue.py", line 177, in get
    item = self._get()
  File "/usr/lib/python3.4/queue.py", line 233, in _get
    return heappop(self.queue)
TypeError: unorderable types: NoneType() < SoundInstance()
INFO : kivy : Stopping child threads... (3 remaining)

**Comment by qcapen** [comment]
Fixed in 0.32
