### ISSUE TITLE
slide_player crash

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#24]
```
INFO : kivy : AudioInterface: Enabling audio playback
INFO : kivy : Base: Start application main loop
INFO : kivy : Base: Leaving application in progress...
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\mpf.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\mpf\commands\__init__.py", line 121, in run_from_command_line
    CommandLineUtility(path).execute()
  File "c:\python34\lib\site-packages\mpf\commands\__init__.py", line 54, in execute
    *self.parse_args())
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 141, in __init__
    machine_path=machine_path).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "c:\python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "c:\python34\lib\site-packages\mpfmc\uix\display.py", line 110, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 195, in displays_initialized
    self._init()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 234, in _init
    self.events.process_event_queue()
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 477, in process_event_queue
    **event[3])
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 412, in _process_event
    result = handler[0](**merged_kwargs)
  File "c:\python34\lib\site-packages\mpfmc\core\mode_controller.py", line 54, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\python34\lib\site-packages\mpfmc\core\mode_controller.py", line 131, in _load_mode
    return Mode(self.mc, config, mode_string, mode_path)
  File "c:\python34\lib\site-packages\mpfmc\core\mode.py", line 47, in __init__
    **item.kwargs)
  File "c:\python34\lib\site-packages\mpf\core\config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "c:\python34\lib\site-packages\mpfmc\config_players\slide_player.py", line 238, in validate_config
    for key in slide_settings.keys():
AttributeError: 'int' object has no attribute 'keys'
```

**Comment by toomanybrians** [comment]
moved to mpf issue
