### ISSUE TITLE
BCP Crash on machine_variable update

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#270]
https://groups.google.com/forum/#!topic/mpf-users/G0CrepxePek

```
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 190, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 581, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7700)
  File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7577)
  File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7498)
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
  File "c:\python34\lib\site-packages\mpfmc\core\bcp_processor.py", line 127, in _get_from_queue
    self._process_command(cmd, **kwargs)
  File "c:\python34\lib\site-packages\mpfmc\core\bcp_processor.py", line 145, in _process_command
    self.bcp_commands[bcp_command](**kwargs)
TypeError: _bcp_machine_variable() missing 1 required positional argument: 'value'
```

Cannot reproduce currently. We could suppress the error but we still should try to find the root cause.

**Comment by jabdoa2** [comment]
fixed in 0.50
