### ISSUE TITLE
sound_player crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#286]
```
kivy: Base: Leaving application in progress...
kivy: Argument 'name' has incorrect type (expected str, got NoneType)
Traceback (most recent call last):
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/commands/mc.py", line 199, in __init__
    thread_stopper=thread_stopper).run()
  File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/usr/local/lib/python3.5/dist-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7352)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7229)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7150)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:3260)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/mc.py", line 455, in tick
    self.events.process_event_queue()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 673, in process_event_queue
    **event[3])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 642, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 601, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/config_player.py", line 286, in config_play_callback
    self.play(settings=settings, context=context, calling_context=calling_context, priority=priority, **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/config_players/sound_player.py", line 105, in play
    track = self.machine.sound_system.audio_interface.get_track_by_name(s['track'])
TypeError: Argument 'name' has incorrect type (expected str, got NoneType)
```

**Comment by jabdoa2** [comment]
This seems to be caused by playing a sound from a sound_pool
