### ISSUE TITLE
Assign tracks for sounds based on folder

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#290]
mpfmc.tests.test_Audio_GStreamer.TestAudioGStreamer failed because this does not work

```
======================================================================
FAIL: test_retrigger_streamed_sound (mpfmc.tests.test_Audio_GStreamer.TestAudioGStreamer)
Tests retriggering a streamed sound (play, stop, play) (using gstreamer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/tests/MpfMcTestCase.py", line 188, in setUp
    self._start_app_as_slave()
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/tests/MpfMcTestCase.py", line 225, in _start_app_as_slave
    self.advance_time()
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/tests/MpfMcTestCase.py", line 94, in advance_time
    EventLoop.idle()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/usr/local/lib/python3.5/dist-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7352)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7229)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7150)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:3260)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/uix/display.py", line 164, in _displays_initialized
    self.mc.displays_initialized()
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/mc.py", line 271, in displays_initialized
    self._init()
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/mc.py", line 318, in _init
    self.events.process_event_queue()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 682, in process_event_queue
    **event[3])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 651, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 610, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/assets.py", line 196, in _create_assets
    self._create_assets_from_disk(config=self.machine.machine_config)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/assets.py", line 321, in _create_assets_from_disk
    config=config[ac.disk_asset_section][asset])
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/assets/sound.py", line 253, in __init__
    raise AssertionError("Sound {} does not have a valid track.".format(name))
AssertionError: Sound bass_synth does not have a valid track.
```

This seems to have no effect:
```
assets:
  sounds:
    default:
      load: preload
    voice:
      load: preload
      track: voice
    sfx:
      load: on_demand
      track: sfx
    music:
      load: on_demand
track: music
```

**Comment by qcapen** [comment]
There is now a test that ensure the default asset settings are working (such as track) for sounds. This bug has been fixed.
