### ISSUE TITLE
Sound system crash

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#293]
```
======================================================================
ERROR: test_typical_sound_system (mpfmc.tests.test_Audio.TestAudio)
Tests the sound system and audio interface with typical settings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "mpfmc\core\audio\track_standard.pyx", line 495, in mpfmc.core.audio.track_standard.TrackStandard.play_sound (/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/audio/track_standard.c:7963)
OverflowError: value too large to convert to int

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/tests/test_Audio.py", line 131, in test_typical_sound_system
    self.advance_real_time(1)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/tests/MpfMcTestCase.py", line 100, in advance_real_time
    EventLoop.idle()
  File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/usr/local/lib/python3.5/dist-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7352)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7229)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:7150)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip-build-tsgpre07/kivy/kivy/_clock.c:3260)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/mc.py", line 455, in tick
    self.events.process_event_queue()
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 697, in process_event_queue
    **event[3])
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 666, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/events.py", line 624, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf/mpf/core/config_player.py", line 330, in config_play_callback
    **kwargs)
  File "/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/config_players/sound_player.py", line 115, in play
    track.play_sound(sound, context, s)
  File "mpfmc\core\audio\track_standard.pyx", line 597, in mpfmc.core.audio.track_standard.TrackStandard.play_sound (/data/home/jan/cloud/flipper/src/mpf-mc/mpfmc/core/audio/track_standard.c:9598)
mpfmc.core.audio.audio_exception.AudioException: Track sfx play_sound encountered an unexpected exception while attempting to play the 264828_text sound.
```

**Comment by jabdoa2** [comment]
Fixed with a252d5d0eed08cc53dc07f73320bec68d26876f4
