### ISSUE TITLE
Lower casing issue with sounds

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#295]
2017-12-31 11:09:03,655 : AssetManager : ERROR: The file associated with the disk-based asset 'What_Was_That' declared in the 'sounds' config section could not be found
2017-12-31 11:09:03,656 : kivy : Base: Leaving application in progress...
2017-12-31 11:09:03,656 : kivy : The file associated with the disk-based asset 'What_Was_That' declared in the 'sounds' config section could not be found
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 199, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\kivy\app.py", line 828, in run
    runTouchApp()
  File "c:\python34\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "c:\python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "c:\python34\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\python34\lib\site-packages\kivy\clock.py", line 581, in tick
    self._process_events()

**Comment by jabdoa2** [comment]
fixed in https://github.com/missionpinball/mpf/commit/2d110b60e27322d311857f1ac3f4a5d8c84c1a05
