### ISSUE TITLE
Slide Player crashes in mc

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#41]
Mode does not have any slides.
```
Traceback (most recent call last):
  File "/usr/local/bin/mpf", line 9, in <module>
    load_entry_point('mpf==0.30.0.dev1223', 'console_scripts', 'mpf')()
  File "/mpf/commands/__init__.py", line 121, in run_from_command_line
    CommandLineUtility(path).execute()
  File "/mpf/commands/__init__.py", line 54, in execute
    *self.parse_args())
  File "/mpfmc/commands/mc.py", line 141, in __init__
    machine_path=machine_path).run()
  File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/local/lib/python3.4/dist-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/usr/local/lib/python3.4/dist-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/local/lib/python3.4/dist-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "/mpfmc/uix/display.py", line 114, in _displays_initialized
    self.mc.displays_initialized()
  File "/mpfmc/core/mc.py", line 197, in displays_initialized
    self._init()
  File "/mpfmc/core/mc.py", line 236, in _init
    self.events.process_event_queue()
  File "/mpf/core/events.py", line 482, in process_event_queue
    **event[3])
  File "/mpf/core/events.py", line 417, in _process_event
    result = handler[0](**merged_kwargs)
  File "/mpfmc/core/mode_controller.py", line 54, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "/mpfmc/core/mode_controller.py", line 133, in _load_mode
    return Mode(self.mc, config, mode_string, mode_path)
  File "/mpfmc/core/mode.py", line 47, in __init__
    **item.kwargs)
  File "/mpf/core/config_player.py", line 131, in process_mode_config
    config = self.validate_config(config)
  File "/mpfmc/config_players/slide_player.py", line 213, in validate_config
    settings = {settings: dict()}
TypeError: unhashable type: 'list' 
```

**Comment by toomanybrians** [comment]
@jabdoa2: what did the config look like that caused this? I think it's a mal-formed config that we just need a better error for?

**Comment by jabdoa2** [comment]
I debugged it some more. Probably a left over from the migration. I actually had a "slide_player:" section in my mode. Should not be there, right? Looking at the tests it should be a "slides:" section. I think we can close this for now.

After 0.30 I want to refactor all the config loading/device creation in modes.
