### ISSUE TITLE
Audio error in 0.57.devXX.

### ISSUE THREAD

**Issue by Pucksnok** [missionpinball/mpf-mc#454]
Hello.
Just installed a fresh computer with Windows 11 and Python 3,11 and tried the latest dev version. PATH is correct so shouldn't be the issue. I have tried to install Python both as user and for everyone, (PATH manually cleared between and reboot done).

mpf                 0.57.0.dev31
mpf-mc              0.57.0.dev10
mpf-monitor         0.57.0.dev3

I checked out https://github.com/missionpinball/mpf-mc/pull/452/commits/b4601016a39494bdc0927a24f1e8d84ff8b8b6dc#top and I'm not sure if this is the same issue or not.

Error...

14:47:54.582 : INFO [mpfmc] Mission Pinball Framework Media Controller (MPF-MC) v0.57.0.dev10. Requires MPF v0.57.0.dev19 or newer.
14:47:54.583 : INFO [mpfmc] Found MPF v0.57.0.dev31
14:47:54.583 : INFO [mpfmc] Machine path: C:\Pinball
14:47:54.583 : INFO [mpfmc] Starting clock at 60.0Hz
14:47:54.606 : INFO [kivy] Text: Provider: pil(['text_sdl2'] ignored)
14:47:54.628 : ERROR [root] DLL load failed while importing sound_file: Det går inte att hitta den angivna proceduren.
Traceback (most recent call last):
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\commands\mc.py", line 215, in __init__
    MpfMc(options=vars(args),
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\core\mc.py", line 148, in __init__
    create_config_collections(self, self.machine_config['mpf-mc']['config_collections'])
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\core\config_collection.py", line 82, in create_config_collections
    imported_module = import_module(module)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\config_collections\sound_loop_set.py", line 1, in <module>
    from mpfmc.core.audio.audio_exception import AudioException
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\core\audio\__init__.py", line 7, in <module>
    from mpfmc.core.audio.audio_interface import AudioInterface
  File "mpfmc/core/audio/audio_interface.pyx", line 1, in init mpfmc.core.audio.audio_interface
ImportError: DLL load failed while importing sound_file: Det går inte att hitta den angivna proceduren.
14:47:54.631 : INFO [root] Stopping child threads... (0 remaining)
14:47:54.631 : INFO [root] All child threads stopped.

C:\Pinball>pip list
Package             Version
------------------- ------------
asciimatics         1.14.0
certifi             2023.7.22
charset-normalizer  3.3.2
docutils            0.20.1
ffpyplayer          4.5.0
future              0.18.3
idna                3.4
Kivy                2.2.1
kivy-deps.angle     0.3.3
kivy-deps.glew      0.3.1
kivy-deps.gstreamer 0.3.3
kivy-deps.sdl2      0.6.0
Kivy-Garden         0.1.5
mpf                 0.57.0.dev31
mpf-mc              0.57.0.dev10
mpf-monitor         0.57.0.dev3
packaging           23.1
Pillow              10.1.0
pip                 23.3.1
prompt-toolkit      3.0.39
psutil              5.9.5
pyfiglet            1.0.2
Pygments            2.16.1
pypiwin32           223
PyQt6               6.6.0
PyQt6-Qt6           6.6.0
PyQt6-sip           13.6.0
pyserial            3.5
pyserial-asyncio    0.6
pywin32             306
requests            2.31.0
ruamel.yaml         0.17.32
ruamel.yaml.clib    0.2.8
setuptools          65.5.0
sortedcontainers    2.4.0
terminaltables      3.1.10
urllib3             2.0.7
wcwidth             0.2.9

C:\Pinball>

**Comment by Pucksnok** [comment]
Can add that I also tried with mc_demo downloaded from latest dev, same error.

**Comment by toomanybrians** [comment]
This is a bit of a different error I think, because if the audio fails to import I think it will print that friendly message in the logs? There might be more information in these previous issues: #450 #436 

I don't have a Windows machine so I'm not able to test. (And I don't know Cython either, which is what the audio system is written in, so apart from me getting it to build without errors, I don't know what else to do?)

So I think we're back to needing to find someone who knows Cython and Python and has Windows who can dig into this?

**Comment by Pucksnok** [comment]
This is in my MC-log.

2023-11-02 14:47:54,119 : kivy : deps: Successfully imported "kivy_deps.gstreamer" 0.3.3
2023-11-02 14:47:54,119 : kivy : deps: Successfully imported "kivy_deps.angle" 0.3.3
2023-11-02 14:47:54,119 : kivy : deps: Successfully imported "kivy_deps.glew" 0.3.1
2023-11-02 14:47:54,119 : kivy : deps: Successfully imported "kivy_deps.sdl2" 0.6.0
2023-11-02 14:47:54,120 : kivy : Kivy: v2.2.1
2023-11-02 14:47:54,120 : kivy : Kivy: Installed at "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\__init__.py"
2023-11-02 14:47:54,120 : kivy : Python: v3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
2023-11-02 14:47:54,121 : kivy : Python: Interpreter at "C:\Users\Johan\AppData\Local\Programs\Python\Python311\python.exe"
2023-11-02 14:47:54,138 : kivy : Factory: 190 symbols loaded
2023-11-02 14:47:54,272 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
2023-11-02 14:47:54,454 : kivy : VideoGstplayer: Using Gstreamer 1.18.5.0
2023-11-02 14:47:54,454 : kivy : Video: Provider: gstplayer
2023-11-02 14:47:54,481 : root : Error importing MPF-MC audio library. Audio will be disabled.
2023-11-02 14:47:54,481 : root : *** [[[[[[[[[[[[[[[[[[[ NO AUDIO ]]]]]]]]]]]]]]]]] ***
2023-11-02 14:47:54,481 : root : DLL load failed while importing sound_file: Det g r inte att hitta den angivna proceduren.
Traceback (most recent call last):
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\core\mc.py", line 52, in <module>
    from mpfmc.core.audio.audio_interface import AudioInterface
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mpfmc\core\audio\__init__.py", line 7, in <module>
    from mpfmc.core.audio.audio_interface import AudioInterface
  File "mpfmc/core/audio/audio_interface.pyx", line 1, in init mpfmc.core.audio.audio_interface
ImportError: DLL load failed while importing sound_file: Det g r inte att hitta den angivna proceduren.

**Comment by toomanybrians** [comment]
Ah, ok so that is the same error as those other issues. I still have no idea how to fix it, but at least it makes sense now.
